name: divine_camera
description: "Camera plugin to record videos." 
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: '>=3.3.0'

dependencies:
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  plugin:
    platforms:
      android:
        package: co.openvine.divine_camera
        pluginClass: DivineCameraPlugin
      ios:
        pluginClass: DivineCameraPlugin
