name: videos_repository
description: Repository for managing video operations with Nostr.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  db_client:
    path: ../db_client
  nostr_client:
    path: ../nostr_client
  nostr_sdk:
    path: ../nostr_sdk
  rxdart: ^0.28.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
